/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fun_with_java_enums;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void alwaysTrue() {
        assertEquals(1, 1);
    }
}
